### ISSUE TITLE
initilizing skill gives error message

### ISSUE THREAD

**Issue by rocus** [JoergZ2/mympdplaylist-skill#1]
When the skill is initialized python gives an error message: __init__ failed with AttributeError bool object has no attribute lower.
Apparently this is during this line: self.placement_1 = self.settings.get ('placement_1' , False).lower()

I suspect that the settings file is incorrect. It is not clear to me if I should edit the settingsmeta.yaml file in the dir
/opt/mycroft/skills/mympdplaylist-skill.joergz2 .
Or should I make a settings.json file in ~/.config/mycroft/skills/mympd...  directory? If so can you give me an example of this json file. Should I put 5 radio entries in this file even if I start with only 1 mpd player.

**Comment by krisgesling** [comment]
Hey, if you change the start of the `__init__.py` to something like this it should work:

```python
class Mympdplaylist(MycroftSkill):
    def __init__(self):
        super(Mympdplaylist, self).__init__(name="My MPD playlist manager")

    def initialize(self):
        self.settings_change_callback = self.on_settings_changed
        self.on_settings_changed()
        self.same_device = DeviceApi()
        info = self.same_device.get(); self.same_device = info['description'].lower()
    
    def on_settings_changed(self):
        self.host = self.settings.get('radio_1')
        self.port = self.settings.get('port_1')
        self.placement_1 = self.settings.get('placement_1', '').lower()
        self.placement_2 = self.settings.get('placement_2', '').lower()
        self.placement_3 = self.settings.get('placement_3', '').lower()
        self.placement_4 = self.settings.get('placement_4', '').lower()
        self.placement_5 = self.settings.get('placement_5', '').lower()
        self.placements = {self.placement_1:[self.settings.get('radio_1'),self.settings.get('port_1')],\
                           self.placement_2:[self.settings.get('radio_2'),self.settings.get('port_2')],\
                           self.placement_3:[self.settings.get('radio_3'),self.settings.get('port_3')],\
                           self.placement_4:[self.settings.get('radio_4'),self.settings.get('port_4')],\
                           self.placement_5:[self.settings.get('radio_5'),self.settings.get('port_5')]}
```

This assigns any undefined placement settings to a blank string rather than the Boolean `False`. So they have a `lower()` method but would still evaluate to False if tested in a conditional, eg `if not self.placement_1`

With this change the Skill will load without settings existing, which will let it sync with the backend. Anytime the settings change the `on_settings_changed()` method will get called and updated `self.placements`

**Comment by rocus** [comment]
Hi Kris, thanks for your answer. I cannot judge if your solution is working but I think it will. 
As I often do after posting a question somewhere , I found a solution myself. I sort of reverse engineered the settings.json myself:

{"placement_1" : "Salon" , "radio_1" : "10.0.2.210" , "port_1" : "6600" , "placement_2"  ........ "placement_5"..... }

Then the skill loads OK and the settings.json file is later rewritten with mycroftfirstrun entry at the end.
It is still unclear to me why there are two settings files. Is the settingsmeta.yaml file meant for the configuration setting via the mycroft skills site? The settings.json file in the ~/.config/mycroft .... directory is obviously necessary (in this skill) ; why is this file not present in the github directory?  Or am I missing something?

**Comment by krisgesling** [comment]
`settingsmeta.json` defines what settings exist, where as `settings.json` contains the values of the settings.

So the Skill directory shouldn't need to be writable by the user running Mycroft, where as the settings.json file should which is why it is in `~/.config/mycroft`.

**Comment by JoergZ2** [comment]
I tried the code of @krisgesling. It's not working for me. I understand the intention and approximately the sense of the position of the instructions. But I get either a KeyError from Python or a ConnectionError from mpc library. For the moment I've not enough time to look deeper at that issue and it's working in my environment. I hope I can have a look in October.

**Comment by JoergZ2** [comment]
Fortunately, I have some time right now. I'm a bit perplex. On the one hand, the use of self.settings.get() corresponds exactly to the Mycroft documentation:
https://mycroft-ai.gitbook.io/docs/skill-development/skill-structure/skill-settings#reading-settings

@rocus I don't have all five MPD servers occupied in my account. The skill still works for me. The cause should be somewhere else. Have you assigned a room (placement) to your Mycroft instance in your account (https://account.mycroft.ai/devices)?
Unfortunately I can't reproduce the misbehavior.

@krisgesling I'm not a Python professional but just an amateur but if I remove the settings.get() method from the initialze() function and move it to the on_settings_changed() function, then the data will only be retrieved if something changes in the settings. Or am I wrong there? If nothing changes, then the dictionary self.placements is empty, isn't it?

**Comment by krisgesling** [comment]
Yep, in this case I suggest setting it as a callback when the settings change and calling that function during initialize:
```python
    def initialize(self):
        self.settings_change_callback = self.on_settings_changed
        self.on_settings_changed()
```
This way the function gets executed on Skill load, and then again anytime the settings get modified.

I didn't look at what happens after the Skill loads. Potentially you shouldn't try setting anything up unless the placements dictionary is populated? 

This is also a good reason to initialize attributes/variables in your class constructor (the `__init__` function) so you don't end up in situations where it doesn't yet exist. Eg if `self.placements` was initialized as None or an empty dict, then you can easily check if it has been populated yet.

**Comment by JoergZ2** [comment]
After retesting, I find that krisgesling's code works after all, and I've adopted it. Thanks!
